services:
  ralex-works:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ralex-works
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
